In [4]:
#addition of 2 matrix
matrix1 = [
    [1,2,3,],
    [4,5,6]
]
matrix2 = [
    [6,5,4],
    [1,2,3]
]
result=[
    [0,0,0],
    [0,0,0]
]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        
     result[i][j] = matrix1[i][j] + matrix2[i][j]
        
print("matrix1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

print("\nSum of Matrix1 and Matrix2:")
for row in result:
    print(row)


matrix1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[6, 5, 4]
[1, 2, 3]

Sum of Matrix1 and Matrix2:
[7, 7, 7]
[5, 7, 9]


In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
res = a +b 
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
